
import java.awt.Color;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.*;
import java.awt.event.KeyEvent;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class ExerciseGUI extends javax.swing.JInternalFrame {

    private Lessons lessons;
    private int cursor;
    private int progress;
    private int adjusted;
    
    DefaultHighlighter.DefaultHighlightPainter painter = new DefaultHighlighter.DefaultHighlightPainter(Color.orange);

    /**
     * Creates new form ExerciseGUI
     */
    public ExerciseGUI() {
        initComponents();
        reference_text_area.addKeyListener(this.getKeyListeners()[0]);//создали отдельных слушателей для ввода с клавиатуры для запрещённых к редактированию полей ввода
        entry_text_area.addKeyListener(this.getKeyListeners()[0]);
        //подобие мелькающего курсора:
        DefaultCaret dc = new DefaultCaret();
        dc.setSize(10, 2);
        dc.setBlinkRate(500);//интервал мелькания
        entry_text_area.setCaret(dc);//загружаем в нижнюю часть окна
        entry_text_area.setCaretColor(Color.red);
        dc.setVisible(true);
    }
    private void update_status (boolean mis){
    if(mis == true)status_panel.setBackground(Color.blue);
    else status_panel.setBackground(Color.red);
    }
    public void reveal (Lessons lessons) {
    adjusted = 0;
    this.lessons = lessons;
    title_label.setText(lessons.get_title());
    descr_label.setText(lessons.get_instructions());
    reference_text_area.setText(lessons.get_text());
    entry_text_area.setText("");
    cursor = 0;
    progress = 0;
    }
    private void show_typing_cursor () {
    try{
    reference_text_area.setCaretPosition(cursor);//установить подсветку в место положения курсора
    reference_text_area.getHighlighter().removeAllHighlights();//покучили все подсвеченные элементы и для них убрали всю подсветку
    reference_text_area.getHighlighter().addHighlight(cursor, cursor+1, painter);
    } catch (Exception e){e.printStackTrace();}
    }
    private void handle_key_press(char char_struck){
    handle_key_press_lesson (char_struck);
    if (progress == reference_text_area.getText().length()){
    JOptionPane.showConfirmDialog(this, "You accuracy is " + adjusted +" symbols from "+reference_text_area.getText().length(), "Information", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }    
    }
    private void handle_key_press_lesson (char char_struck){
    if(progress < reference_text_area.getText().length()){
    char char_wanted = reference_text_area.getText().charAt(progress);
    if(char_struck == char_wanted) {//проверяем является ли клавиша, которую ввели, той,
        //которую нужно было вводить
    adjusted++;
    entry_text_area.append(reference_text_area.getText().substring(progress, progress+1));
    progress++; cursor++;
    update_status(true);
    }
    else {
        entry_text_area.append("*");
        progress++; cursor++;
        update_status(false);
                }
    entry_text_area.setCaretPosition(cursor);
    show_typing_cursor();
    }
    }
    private void restart (){
    reveal(lessons);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        toolbar = new javax.swing.JPanel();
        restart_button = new javax.swing.JButton();
        pause_button = new javax.swing.JToggleButton();
        label_panel = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        descr_label = new javax.swing.JLabel();
        status_panel = new javax.swing.JPanel();
        text_panel = new javax.swing.JPanel();
        drill_panel = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        reference_text_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        entry_text_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        restart_button.setText("Restart");
        restart_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_buttonActionPerformed(evt);
            }
        });
        toolbar.add(restart_button);

        pause_button.setText("Pause");
        toolbar.add(pause_button);

        top_panel.add(toolbar);

        title_label.setText("title");
        label_panel.add(title_label);
        label_panel.add(descr_label);

        top_panel.add(label_panel);

        getContentPane().add(top_panel, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout status_panelLayout = new javax.swing.GroupLayout(status_panel);
        status_panel.setLayout(status_panelLayout);
        status_panelLayout.setHorizontalGroup(
            status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        status_panelLayout.setVerticalGroup(
            status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        getContentPane().add(status_panel, java.awt.BorderLayout.SOUTH);

        text_panel.setLayout(new java.awt.CardLayout());

        drill_panel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        reference_text_area.setEditable(false);
        reference_text_area.setColumns(20);
        reference_text_area.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        reference_text_area.setLineWrap(true);
        reference_text_area.setRows(5);
        reference_text_area.setWrapStyleWord(true);
        jScrollPane1.setViewportView(reference_text_area);

        drill_panel.setLeftComponent(jScrollPane1);

        entry_text_area.setEditable(false);
        entry_text_area.setColumns(20);
        entry_text_area.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        entry_text_area.setLineWrap(true);
        entry_text_area.setRows(5);
        entry_text_area.setWrapStyleWord(true);
        jScrollPane2.setViewportView(entry_text_area);

        drill_panel.setRightComponent(jScrollPane2);

        text_panel.add(drill_panel, "card2");

        getContentPane().add(text_panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(!evt.isControlDown()){
            //если была нажата не управляющая клавиша
            char key_pressed = evt.getKeyChar();//присваиваем переменной значение клавиши
            int keycode = evt.getKeyCode();//присваиваем переменной код клавиши(с учётом CapsLock например)
            handle_key_press(key_pressed);
            evt.consume();
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        //в дальнейшем будем фиксировать событие отжатия клавиш, чтобы
        //замерять время выполнения урока
    }//GEN-LAST:event_formKeyReleased

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if ((evt.getKeyCode()==KeyEvent.VK_LEFT)||(evt.getKeyCode()==KeyEvent.VK_RIGHT)||(evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
        entry_text_area.setCaretPosition(cursor);//если были нажаты клавиши стрелок, то вернуть курсор в исходное положение
        }
    }//GEN-LAST:event_formKeyTyped

    private void restart_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_buttonActionPerformed
        restart();
    }//GEN-LAST:event_restart_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExerciseGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descr_label;
    private javax.swing.JSplitPane drill_panel;
    private javax.swing.JTextArea entry_text_area;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel label_panel;
    private javax.swing.JToggleButton pause_button;
    private javax.swing.JTextArea reference_text_area;
    private javax.swing.JButton restart_button;
    private javax.swing.JPanel status_panel;
    private javax.swing.JPanel text_panel;
    private javax.swing.JLabel title_label;
    private javax.swing.JPanel toolbar;
    private javax.swing.JPanel top_panel;
    // End of variables declaration//GEN-END:variables
  
}
