/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import javax.swing.*;
public abstract class KBIcon extends javax.swing.JPanel {

    public static final int DEFAULT_SIZE = 30;
    protected String legend;//хранить то, что написано на клавишах
    protected boolean show_legend = true;
    protected Dimension pref_size;
    protected Color highlight_color;
    
    public KBIcon(String legend, int unit_size, int width_factor,int height_factor) {
        initComponents();
        this.pref_size = new Dimension(unit_size * width_factor/100, unit_size * height_factor/100);
        set_legend(legend);
    }
    public KBIcon(String legend, int width_factor){
    this(legend, DEFAULT_SIZE, width_factor,100);
    }
    public synchronized Dimension getPreferredSize(){
    return (pref_size);
    }
    public synchronized Dimension getMinimumSize(){
    return (pref_size);
    }
    public synchronized void update (Graphics g){
    paint(g);
    }
    public synchronized String get_legend(){
    return(legend);
    }
    public synchronized void set_legend(String legend){
    if(!legend.equals(this.legend)){
    this.legend = legend;
    repaint();
    }
    }
    public synchronized void show_legend(boolean show_legend){
    if(show_legend!= this.show_legend){
    this.show_legend = show_legend;
    repaint();
    }
    }
    
    public synchronized void set_highlight (Color color){
    if(color != highlight_color){
    highlight_color = color;
    repaint();
    }
    }
    public synchronized void clear_highlight(){
    set_highlight(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
