
import java.awt.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainWindow extends javax.swing.JFrame {
private ExerciseGUI exercise;
private KeyboardGUI keyboard;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.setTitle("Typing");
        
        initComponents();
        exercise = new ExerciseGUI();
        exercise.pack();
        exercise.validate();
        exercise.reveal(new Lessons("Lesson 1", "Please Type", "fjdk lsl; dlkadjf ;lakdjfadf"));
        jDesktopPane1.add(exercise);
        exercise.setResizable(true);
        exercise.setVisible(true);
        exercise.setSize(490, 300);
                
        keyboard = new KeyboardGUI();
        keyboard.pack();
        keyboard.validate();
        jDesktopPane1.add(keyboard);
        keyboard.setResizable(true);
        keyboard.setVisible(true);
        keyboard.setSize(490, 300);
        this.setSize(500, 400);
        this.centered();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menu_bar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        file_exit = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        help_about = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        file_menu.setMnemonic('F');
        file_menu.setText("File");

        file_exit.setText("Exit");
        file_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_exitActionPerformed(evt);
            }
        });
        file_menu.add(file_exit);

        menu_bar.add(file_menu);

        help_menu.setMnemonic('H');
        help_menu.setText("Help");
        help_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_menuActionPerformed(evt);
            }
        });

        help_about.setText("About");
        help_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_aboutActionPerformed(evt);
            }
        });
        help_menu.add(help_about);

        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        help_menu.add(help);

        menu_bar.add(help_menu);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void help_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_aboutActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Under Construction...", "Information", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_help_aboutActionPerformed

    private void file_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_exitActionPerformed
        exit();
    }//GEN-LAST:event_file_exitActionPerformed
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exit();
    }//GEN-LAST:event_formWindowClosing

    private void help_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_menuActionPerformed
        //int result = JOptionPane.showConfirmDialog(this, "Under Construction...", "Information", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_help_menuActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Under Construction...", "Information", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpActionPerformed
    private void exit (){
    int result = JOptionPane.showConfirmDialog(this, "Do you really want to exit?", "Information", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result != JOptionPane.NO_OPTION){//если нажата не клавиша "нет", то выйти из программы
        dispose ();
        System.exit(0);
}
    }
    private void centered (){
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();//записываем в переменную размер экрана
    Dimension frameSize = this.getSize();//dimension это класс для измерений
    if (frameSize.height > screenSize.height){
        frameSize.height = screenSize.height;//если окна больше высоты экрана, то мы их выравниваем
                }
    if (frameSize.width > screenSize.width){
        frameSize.width = screenSize.width;
                }
    //задаём координаты левого верхнего угла окна для центрирования
    this.setLocation((screenSize.width - frameSize.width)/2, (screenSize.height - frameSize.height)/2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem file_exit;
    private javax.swing.JMenu file_menu;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenuItem help_about;
    private javax.swing.JMenu help_menu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar menu_bar;
    // End of variables declaration//GEN-END:variables
}
